#!/bin/sh

export HOME=/home/user

[ -z "${JENKINS_SLAVE_SSH_PUBKEY}" ] || {
  mkdir ${HOME}/.ssh
  echo "${JENKINS_SLAVE_SSH_PUBKEY}" > ${HOME}/.ssh/authorized_keys
  chown -R user:user ${HOME}/.ssh
  chmod 0700 -R ${HOME}/.ssh
}

exec /usr/sbin/sshd -D
